### ISSUE TITLE
Show/hide columns

### ISSUE THREAD

**Issue by pedrofs** [validide/resizable-table-columns#20]
Hi, @validide.

Congrats on the lib. Great work!

I implement a simple way to show and hide columns outside the library. Would it be an exciting feature to have here?

By the way, how is the library maintenance?

Thanks.

**Comment by validide** [comment]
Hi @pedrofs,


Thank you for the feedback, I really appreciate it.

The library was started some years ago and it surely is not up to the latest best practices. "It works" for most of the cases even though from time to time I can see some strange miss-alignment issues. Issues on which I have already spent more time and got more frustrated than I would have liked to.

At the moment I do not have the time to invest in improving the the library so I would say it is in "maintenance" mode. I am not adding any new feature to it, only security updates. 

I have mixed feeling about adding that functionality to the library as that feels more of a "data grid" kind of feature. There are already some nice "Data grid" libraries out in community that might be more mature and better supported. 

You are however welcomed to fork the library and add the functionality to it.
