### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by wisamidris7** [validide/resizable-table-columns#26]

**Comment by validide** [comment]
There is none.

**Comment by wisamidris7** [comment]
i don't understand

> There is none.

**Comment by validide** [comment]
1. Did you read the project [status](https://github.com/validide/resizable-table-columns?tab=readme-ov-file#status)?
2. Considering you did not provide any description to the issue I do not know what you want. If you want to fork the project and implement RTL support yourself you are welcomed to.
