### ISSUE TITLE
If you can make rtl

### ISSUE THREAD

**Issue by wisamidris7** [validide/resizable-table-columns#28]
If you can make rtl and give me js in github or make branch whatever even if it has problem cause i really need rtl it's really important

If you can?

**Comment by validide** [comment]
Feel free to fork the project and try to implement this.

**Comment by wisamidris7** [comment]
i'm just bad at js

**Comment by wisamidris7** [comment]
i'm aspnetcore developer C#

**Comment by wisamidris7** [comment]
just tell me the method or the line that responsible for resizing and i will edit it in my self
